// Autogenerated-compatible from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// This file provides Swift protocol definitions for the Pigeon APIs
// defined in pigeons/pigeon.dart

import Flutter
import Foundation

// MARK: - Pigeon Codec

class PigeonApiCodec: FlutterStandardMessageCodec {
    static let shared = PigeonApiCodec()
}

// MARK: - AppConfig

/// Generated from Pigeon: AppConfig
protocol AppConfig {
    func isWakeLockEnabled() throws -> Bool
    func setWakeLockEnabled(enabled: Bool) throws
    func isStartAtBootEnabled() throws -> Bool
    func setStartAtBootEnabled(enabled: Bool) throws
    func isAutoCheckUpdateEnabled() throws -> Bool
    func setAutoCheckUpdateEnabled(enabled: Bool) throws
    func isAutoOpenWebPageEnabled() throws -> Bool
    func setAutoOpenWebPageEnabled(enabled: Bool) throws
    func getDataDir() throws -> String
    func setDataDir(dir: String) throws
    func isSilentJumpAppEnabled() throws -> Bool
    func setSilentJumpAppEnabled(enabled: Bool) throws
}

class AppConfigSetup {
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppConfig?) {
        let channelSuffix = ""

        let isWakeLockEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.isWakeLockEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isWakeLockEnabledChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isWakeLockEnabled()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isWakeLockEnabledChannel.setMessageHandler(nil)
        }

        let setWakeLockEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setWakeLockEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setWakeLockEnabledChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enabled = args[0] as! Bool
                do {
                    try api.setWakeLockEnabled(enabled: enabled)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setWakeLockEnabledChannel.setMessageHandler(nil)
        }

        let isStartAtBootEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.isStartAtBootEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isStartAtBootEnabledChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isStartAtBootEnabled()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isStartAtBootEnabledChannel.setMessageHandler(nil)
        }

        let setStartAtBootEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setStartAtBootEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setStartAtBootEnabledChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enabled = args[0] as! Bool
                do {
                    try api.setStartAtBootEnabled(enabled: enabled)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setStartAtBootEnabledChannel.setMessageHandler(nil)
        }

        let isAutoCheckUpdateEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.isAutoCheckUpdateEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isAutoCheckUpdateEnabledChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isAutoCheckUpdateEnabled()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isAutoCheckUpdateEnabledChannel.setMessageHandler(nil)
        }

        let setAutoCheckUpdateEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setAutoCheckUpdateEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setAutoCheckUpdateEnabledChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enabled = args[0] as! Bool
                do {
                    try api.setAutoCheckUpdateEnabled(enabled: enabled)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setAutoCheckUpdateEnabledChannel.setMessageHandler(nil)
        }

        let isAutoOpenWebPageEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.isAutoOpenWebPageEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isAutoOpenWebPageEnabledChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isAutoOpenWebPageEnabled()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isAutoOpenWebPageEnabledChannel.setMessageHandler(nil)
        }

        let setAutoOpenWebPageEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setAutoOpenWebPageEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setAutoOpenWebPageEnabledChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enabled = args[0] as! Bool
                do {
                    try api.setAutoOpenWebPageEnabled(enabled: enabled)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setAutoOpenWebPageEnabledChannel.setMessageHandler(nil)
        }

        let getDataDirChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.getDataDir\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getDataDirChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getDataDir()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getDataDirChannel.setMessageHandler(nil)
        }

        let setDataDirChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setDataDir\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setDataDirChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let dir = args[0] as! String
                do {
                    try api.setDataDir(dir: dir)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setDataDirChannel.setMessageHandler(nil)
        }

        let isSilentJumpAppEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.isSilentJumpAppEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isSilentJumpAppEnabledChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isSilentJumpAppEnabled()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isSilentJumpAppEnabledChannel.setMessageHandler(nil)
        }

        let setSilentJumpAppEnabledChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.AppConfig.setSilentJumpAppEnabled\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setSilentJumpAppEnabledChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enabled = args[0] as! Bool
                do {
                    try api.setSilentJumpAppEnabled(enabled: enabled)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setSilentJumpAppEnabledChannel.setMessageHandler(nil)
        }
    }
}

// MARK: - NativeCommon

/// Generated from Pigeon: NativeCommon
protocol NativeCommon {
    func startActivityFromUri(intentUri: String) throws -> Bool
    func getDeviceSdkInt() throws -> Int64
    func getDeviceCPUABI() throws -> String
    func getVersionName() throws -> String
    func getVersionCode() throws -> Int64
    func toast(msg: String) throws
    func longToast(msg: String) throws
}

class NativeCommonSetup {
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeCommon?) {
        let channelSuffix = ""

        let startActivityFromUriChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.startActivityFromUri\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            startActivityFromUriChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let intentUri = args[0] as! String
                do {
                    let result = try api.startActivityFromUri(intentUri: intentUri)
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            startActivityFromUriChannel.setMessageHandler(nil)
        }

        let getDeviceSdkIntChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.getDeviceSdkInt\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getDeviceSdkIntChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getDeviceSdkInt()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getDeviceSdkIntChannel.setMessageHandler(nil)
        }

        let getDeviceCPUABIChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.getDeviceCPUABI\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getDeviceCPUABIChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getDeviceCPUABI()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getDeviceCPUABIChannel.setMessageHandler(nil)
        }

        let getVersionNameChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.getVersionName\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getVersionNameChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getVersionName()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getVersionNameChannel.setMessageHandler(nil)
        }

        let getVersionCodeChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.getVersionCode\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getVersionCodeChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getVersionCode()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getVersionCodeChannel.setMessageHandler(nil)
        }

        let toastChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.toast\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            toastChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let msg = args[0] as! String
                do {
                    try api.toast(msg: msg)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            toastChannel.setMessageHandler(nil)
        }

        let longToastChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.NativeCommon.longToast\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            longToastChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let msg = args[0] as! String
                do {
                    try api.longToast(msg: msg)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            longToastChannel.setMessageHandler(nil)
        }
    }
}

// MARK: - Android

/// Generated from Pigeon: Android (used on both Android and iOS)
protocol Android {
    func addShortcut() throws
    func startService() throws
    func setAdminPwd(pwd: String) throws
    func getOpenListHttpPort() throws -> Int64
    func isRunning() throws -> Bool
    func getOpenListVersion() throws -> String
}

class AndroidSetup {
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Android?) {
        let channelSuffix = ""

        let addShortcutChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.addShortcut\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            addShortcutChannel.setMessageHandler { _, reply in
                do {
                    try api.addShortcut()
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            addShortcutChannel.setMessageHandler(nil)
        }

        let startServiceChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.startService\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            startServiceChannel.setMessageHandler { _, reply in
                do {
                    try api.startService()
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            startServiceChannel.setMessageHandler(nil)
        }

        let setAdminPwdChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.setAdminPwd\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setAdminPwdChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let pwd = args[0] as! String
                do {
                    try api.setAdminPwd(pwd: pwd)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setAdminPwdChannel.setMessageHandler(nil)
        }

        let getOpenListHttpPortChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.getOpenListHttpPort\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getOpenListHttpPortChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getOpenListHttpPort()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getOpenListHttpPortChannel.setMessageHandler(nil)
        }

        let isRunningChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.isRunning\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isRunningChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isRunning()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isRunningChannel.setMessageHandler(nil)
        }

        let getOpenListVersionChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Android.getOpenListVersion\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getOpenListVersionChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getOpenListVersion()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getOpenListVersionChannel.setMessageHandler(nil)
        }
    }
}

// MARK: - Event (FlutterApi)

/// Generated from Pigeon: Event (Flutter -> Native callbacks)
protocol EventProtocol {
    func onServiceStatusChanged(isRunning: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
    func onServerLog(level: Int64, time: String, log: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}

class Event: EventProtocol {
    private let binaryMessenger: FlutterBinaryMessenger

    init(binaryMessenger: FlutterBinaryMessenger) {
        self.binaryMessenger = binaryMessenger
    }

    func onServiceStatusChanged(isRunning: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
        let channel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Event.onServiceStatusChanged",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        channel.sendMessage([isRunning]) { _ in
            completion(.success(()))
        }
    }

    func onServerLog(level: Int64, time: String, log: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
        let channel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.Event.onServerLog",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        channel.sendMessage([level, time, log]) { _ in
            completion(.success(()))
        }
    }
}

// MARK: - EncryptProxy

/// Generated from Pigeon: EncryptProxy (OpenList-Encrypt specific)
protocol EncryptProxy {
    func initEncryptProxy(configPath: String) throws
    func startEncryptProxy() throws
    func stopEncryptProxy() throws
    func restartEncryptProxy() throws
    func isEncryptProxyRunning() throws -> Bool
    func getEncryptProxyPort() throws -> Int64
    func setEncryptAlistHost(host: String, port: Int64, https: Bool) throws
    func setEncryptProxyPort(port: Int64) throws
    func setEncryptEnableH2C(enable: Bool) throws
    func getEncryptEnableH2C() throws -> Bool
    func setEncryptDbExportSyncConfig(enable: Bool, baseUrl: String, intervalSeconds: Int64, authEnabled: Bool, username: String, password: String) throws
    func setEncryptNetworkPolicy(upstreamTimeoutSeconds: Int64, probeTimeoutSeconds: Int64, probeBudgetSeconds: Int64, upstreamBackoffSeconds: Int64, enableLocalBypass: Bool) throws
    func addEncryptPath(path: String, password: String, encType: String, encName: Bool, encSuffix: String) throws
    func updateEncryptPath(index: Int64, path: String, password: String, encType: String, encName: Bool, encSuffix: String, enable: Bool) throws
    func removeEncryptPath(index: Int64) throws
    func getEncryptPathsJson() throws -> String
    func getEncryptConfigJson() throws -> String
    func setEncryptAdminPassword(password: String) throws
    func verifyEncryptAdminPassword(password: String) throws -> Bool
}

class EncryptProxySetup {
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EncryptProxy?) {
        let channelSuffix = ""

        let initEncryptProxyChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.initEncryptProxy\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            initEncryptProxyChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let configPath = args[0] as! String
                do {
                    try api.initEncryptProxy(configPath: configPath)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            initEncryptProxyChannel.setMessageHandler(nil)
        }

        let startEncryptProxyChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.startEncryptProxy\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            startEncryptProxyChannel.setMessageHandler { _, reply in
                do {
                    try api.startEncryptProxy()
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            startEncryptProxyChannel.setMessageHandler(nil)
        }

        let stopEncryptProxyChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.stopEncryptProxy\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            stopEncryptProxyChannel.setMessageHandler { _, reply in
                do {
                    try api.stopEncryptProxy()
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            stopEncryptProxyChannel.setMessageHandler(nil)
        }

        let restartEncryptProxyChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.restartEncryptProxy\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            restartEncryptProxyChannel.setMessageHandler { _, reply in
                do {
                    try api.restartEncryptProxy()
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            restartEncryptProxyChannel.setMessageHandler(nil)
        }

        let isEncryptProxyRunningChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.isEncryptProxyRunning\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            isEncryptProxyRunningChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.isEncryptProxyRunning()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            isEncryptProxyRunningChannel.setMessageHandler(nil)
        }

        let getEncryptProxyPortChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.getEncryptProxyPort\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getEncryptProxyPortChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getEncryptProxyPort()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getEncryptProxyPortChannel.setMessageHandler(nil)
        }

        let setEncryptAlistHostChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptAlistHost\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptAlistHostChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let host = args[0] as! String
                let port = args[1] as! Int64
                let https = args[2] as! Bool
                do {
                    try api.setEncryptAlistHost(host: host, port: port, https: https)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptAlistHostChannel.setMessageHandler(nil)
        }

        let setEncryptProxyPortChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptProxyPort\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptProxyPortChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let port = args[0] as! Int64
                do {
                    try api.setEncryptProxyPort(port: port)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptProxyPortChannel.setMessageHandler(nil)
        }

        let setEncryptEnableH2CChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptEnableH2C\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptEnableH2CChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enable = args[0] as! Bool
                do {
                    try api.setEncryptEnableH2C(enable: enable)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptEnableH2CChannel.setMessageHandler(nil)
        }

        let getEncryptEnableH2CChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.getEncryptEnableH2C\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getEncryptEnableH2CChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getEncryptEnableH2C()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getEncryptEnableH2CChannel.setMessageHandler(nil)
        }

        let setEncryptDbExportSyncConfigChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptDbExportSyncConfig\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptDbExportSyncConfigChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let enable = args[0] as! Bool
                let baseUrl = args[1] as! String
                let intervalSeconds = args[2] as! Int64
                let authEnabled = args[3] as! Bool
                let username = args[4] as! String
                let password = args[5] as! String
                do {
                    try api.setEncryptDbExportSyncConfig(
                        enable: enable, baseUrl: baseUrl, intervalSeconds: intervalSeconds,
                        authEnabled: authEnabled, username: username, password: password
                    )
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptDbExportSyncConfigChannel.setMessageHandler(nil)
        }

        let setEncryptNetworkPolicyChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptNetworkPolicy\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptNetworkPolicyChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let upstreamTimeoutSeconds = args[0] as! Int64
                let probeTimeoutSeconds = args[1] as! Int64
                let probeBudgetSeconds = args[2] as! Int64
                let upstreamBackoffSeconds = args[3] as! Int64
                let enableLocalBypass = args[4] as! Bool
                do {
                    try api.setEncryptNetworkPolicy(
                        upstreamTimeoutSeconds: upstreamTimeoutSeconds,
                        probeTimeoutSeconds: probeTimeoutSeconds,
                        probeBudgetSeconds: probeBudgetSeconds,
                        upstreamBackoffSeconds: upstreamBackoffSeconds,
                        enableLocalBypass: enableLocalBypass
                    )
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptNetworkPolicyChannel.setMessageHandler(nil)
        }

        let addEncryptPathChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.addEncryptPath\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            addEncryptPathChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let path = args[0] as! String
                let password = args[1] as! String
                let encType = args[2] as! String
                let encName = args[3] as! Bool
                let encSuffix = args[4] as! String
                do {
                    try api.addEncryptPath(path: path, password: password, encType: encType, encName: encName, encSuffix: encSuffix)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            addEncryptPathChannel.setMessageHandler(nil)
        }

        let updateEncryptPathChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.updateEncryptPath\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            updateEncryptPathChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let index = args[0] as! Int64
                let path = args[1] as! String
                let password = args[2] as! String
                let encType = args[3] as! String
                let encName = args[4] as! Bool
                let encSuffix = args[5] as! String
                let enable = args[6] as! Bool
                do {
                    try api.updateEncryptPath(index: index, path: path, password: password, encType: encType, encName: encName, encSuffix: encSuffix, enable: enable)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            updateEncryptPathChannel.setMessageHandler(nil)
        }

        let removeEncryptPathChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.removeEncryptPath\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            removeEncryptPathChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let index = args[0] as! Int64
                do {
                    try api.removeEncryptPath(index: index)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            removeEncryptPathChannel.setMessageHandler(nil)
        }

        let getEncryptPathsJsonChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.getEncryptPathsJson\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getEncryptPathsJsonChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getEncryptPathsJson()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getEncryptPathsJsonChannel.setMessageHandler(nil)
        }

        let getEncryptConfigJsonChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.getEncryptConfigJson\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            getEncryptConfigJsonChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getEncryptConfigJson()
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            getEncryptConfigJsonChannel.setMessageHandler(nil)
        }

        let setEncryptAdminPasswordChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.setEncryptAdminPassword\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            setEncryptAdminPasswordChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let password = args[0] as! String
                do {
                    try api.setEncryptAdminPassword(password: password)
                    reply([])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            setEncryptAdminPasswordChannel.setMessageHandler(nil)
        }

        let verifyEncryptAdminPasswordChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.openlist_mobile.EncryptProxy.verifyEncryptAdminPassword\(channelSuffix)",
            binaryMessenger: binaryMessenger,
            codec: PigeonApiCodec.shared
        )
        if let api = api {
            verifyEncryptAdminPasswordChannel.setMessageHandler { message, reply in
                guard let args = message as? [Any?] else { reply(wrapError("Expected list")); return }
                let password = args[0] as! String
                do {
                    let result = try api.verifyEncryptAdminPassword(password: password)
                    reply([result])
                } catch {
                    reply(wrapError(error))
                }
            }
        } else {
            verifyEncryptAdminPasswordChannel.setMessageHandler(nil)
        }
    }
}

// MARK: - Error Helpers

private func wrapError(_ error: Any) -> [Any?] {
    if let pigeonError = error as? PigeonError {
        return [pigeonError.code, pigeonError.message, pigeonError.details]
    }
    if let flutterError = error as? FlutterError {
        return [flutterError.code, flutterError.message, flutterError.details]
    }
    return ["\(error)", "\(type(of: error))", ""]
}
